<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zoo.DAL\Zoo.DAL.csproj" />
    <ProjectReference Include="..\ZOO.DL\Zoo.DL.csproj" />
  </ItemGroup>

</Project>
